### ISSUE TITLE
Mixing components with a facade / Making mixInto's methodNames argument optional

### ISSUE THREAD

**Issue by Rayraz** [jsoverson/Backbone.Augment#4]
I was reading  @derickbailey's blog post on mixins on los techies (http://lostechies.com/derickbailey/2012/10/07/javascript-mixins-beyond-simple-object-extension/) where he sugested a handy way of mixing a component into a target object: https://gist.github.com/3847156#file_5.js 

While I liked the idea, I thought it might become tedious to have to define which properties should and should not be mixed into the target object.

I can imagine a scenario where you might design components specifically with the intention to mix them into other objects. An example of this might be Backbone.EventBinder. In this case, the designer of the component has a very clear idea of which methods and/or properties should be mixed into the target object, and which should not.

I think it would be easier to create a facade, containing only the methods and properties you want to mix into the target object, while keeping the internals of the component private.

This way @derickbailey's gist could still take a target, and a source, but you would no longer need to explicitly list the method names you want to mix into the target. Instead the source's facade already contains only the methods you want to mix in. It would then be desirable to make the methodNames argument(s) optional:

``` javascript
// build a mixin function to take a target that receives the mixin, 
// a source that is the mixin, and a list of methods / attributes to
// copy over to the target

function mixInto(target, source, methodNames){

  // ignore the actual args list and build from arguments so we can
  // be sure to get all of the method names
  var args = Array.prototype.slice.apply(arguments);
  target = args.shift();
  source = args.shift();
  methodNames = args;

  // builds a function with a closure around the source
  // and forwards the method call to the source, passing
  // along the method parameters and setting the context
  var mixMethod = function(target, source, method) {
    target[method] = function(){
      var args = Array.prototype.slice(arguments);
      source[method].apply(source, args);
    }
  }

  // if any method names are supplied, only those methods should be
  // mixed into the target
  if(methodNames.length) {
    var length = methodNames.length;
    for(var i = 0; i < length; i++){
      mixMethod(target, source, methodNames[i]);
    }
  }
  // if no method names are supplied, all properties of the source
  // should be mixed into the target (leaving it upto the source
  // to expose it's public api)
  else {
    for(var method in source) {
      if(source.hasOwnProperty(method) && typeof source[method] === 'function') {
        mixMethod(target, source, method);
      }
    }
  }
}
```

**Comment by jsoverson** [comment]
I think that's a great use, but can still be done without inherent support in augment. Expressly having private functions can be done with a module pattern, e.g.

``` js
var MyAugment = (function(){
  function privateFn() {}

  return {
    augment : function(source) {
      privateFn(source);
      return source;
    }
  }
}())

var NewModel = OldModel.augment(MyAugment);
```

Hybridizing objects that exist on their own and as an augment can be done by providing an augment method on the object. For Backbone style objects, it would be providing an `augment` method as one of the class properties, using EventBinder as an example (untested code):

``` js
var EventBinder = (function(Backbone, _){

  [ cut... ]

  EventBinder.augment = function(OriginalObject) {
    return OriginalObject.extend({
      constructor : function() {
        OriginalObject.prototype.constructor.apply(this,arguments);
        var eventBinder = new EventBinder();
        this.eventBinder = eventBinder;
        this.bindTo = _.bind(eventBinder.bindTo, eventBinder);
        this.unbindFrom = _.bind(eventBinder.unbindFrom, eventBinder);
        this.unbindAll = _.bind(eventBinder.unbindAll, eventBinder);
      }
    });
  }

  _.extend(EventBinder.prototype, {
    /* instance methods */
  });

  return EventBinder;
})(Backbone, _);
```

**Comment by Rayraz** [comment]
I understand your example, but I think a lot of things are happening in the EventBinder.augment method that could be handled by Backbone.Augment itself. Ideally, I think we should have to add as little extra code to our components as possible in order to make them "Backbone.Augment-compatible". As long as it wouldn't greatly reduce the flexibility and usefulness of Backbone.Augment anyways. @derickbailey's suggestion for a mixInto method on Backbone.Augment is a great step in that direction.

Considering the developments in Issue #3 I think I will close this issue for now and continue contributing my thoughts on this in Issue #3
